/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AI_GATEWAY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "CRON_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Cron": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DISCORD_APPLICATION_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_PUBLIC_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Hono": {
      "name": string
      "type": "sst.aws.Function"
    }
    "REDIS_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}